### ISSUE TITLE
astype_executor copy bug

### ISSUE THREAD

**Issue by tkarna** [Python-for-HPC/ramba#15]
On line 5319 `copy` is a boolean arg, not callable:
https://github.com/Python-for-HPC/ramba/blob/13227ea65f31efc1c7d7720f676453acac95d333/ramba/ramba.py#L5315-L5319

Unclear to me what the right fix is, ~`libcopy.deepcopy(self)` seems to work~.

**Comment by DrTodd13** [comment]
@tkarna Should be fixed now.  Please confirm.

**Comment by tkarna** [comment]
@DrTodd13 Commit 508ebd0 fixes the issue, thanks!
